name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:

jobs:
#  build: # make sure build/ci work properly
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v1
#    - run: |
#        npm install
#        npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/debug-action@v1.0.0
    - uses: actions/checkout@v2
    - uses: ./
      if: ${{ github.event_name == 'pull_request' }}
      with:
        path: '**/pmd.xml'
  pr: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/debug-action@v1.0.0
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: ./
      if: ${{ github.event_name == 'pull_request' }}
      with:
        path: '**/pmd.xml'
        ref: ${{ github.event.pull_request.head.sha }}
